### PR TITLE
Translate 'Caffeine' in all languages

### PR DESCRIPTION
**Pull request by pakaoraki**
I noticed that, depend of the language, sometimes 'caffeine' is translated, sometimes not: it could be nice to translate it in all to keep consistency.
Also in Lineageos they translated the menu 'Caffeine', so I thought it could make sens to make this change.

Someone in [#246](https://github.com/eonpatapon/gnome-shell-extension-caffeine/pull/246) had this idea:

> I wonder if i should translate word "Caffeine"?

Let me know if it's something you'd like to see.

### CODE REVIEW

**Comment by pakaoraki** [comment]
I just realized that the Korean file is `ka.po`, I think it suppose to be `ko.po`.

`caffeine@patapon.info/locale/ko/LC_MESSAGES/gnome-shell-extension-caffeine.po → caffeine@patapon.info/locale/ka.po`
I can rename this file in this PR if this change is accepted.

**Comment by stuarthayhurst** [comment]
> I just realized that the Korean file is `ka.po`, I think it suppose to be `ko.po`.
> 
> `caffeine@patapon.info/locale/ko/LC_MESSAGES/gnome-shell-extension-caffeine.po → caffeine@patapon.info/locale/ka.po` I can rename this file in this PR if this change is accepted.

I mean ideally we'd have separate PRs for separate changes to keep rebases simple and following changes, but I suppose it doesn't matter too much for a small change like this

But yes, `ka` seems to be the code for Georgian, that must've been a typo when I moved the translation files, thanks for catching that

**Comment by stuarthayhurst** [comment]
Translating Caffeine in all languages would make sense, as English 'Caffeine' doesn't really have any meaning in other languages.

**Comment by stuarthayhurst** [comment]
Is it worth combining the last 2 commits? Ideally we wouldn't have 2 commits to update the locales.

**Comment by pakaoraki** [comment]
I combined the last 2 commits

**Review by stuarthayhurst — APPROVED** [review]
Thanks :)

**Pull request merged**
