### PR TITLE
Complete spanish translations

### PR DESCRIPTION
**Pull request by delthia**
Hi,
I've completed the Spanish translations for this project, however, here are some things I'd like to mention:

- I've changed the name of the project in the Spanish translations to not be translated. Before in the translations *caffeine* had been translated to Spanish but, as it is the project name's, I think it is more appropriate to have it maintain its original name.
-  There is a translation that is missing, and some that I think that could be more clearly translated. If I can think of them, I'll add the change. In case the PR is approved and I later come up with better translations, I'll be sure to contribute again

Thanks

### CODE REVIEW

**Comment by stuarthayhurst** [comment]
#277 changed the translation behaviour of the project name, I believe the move was for consistency, and that 'Caffeine' doesn't really have meaning in other languages, the same way that in English it relates to keeping awake.

Anyway, thanks for the updates, if you think there's more to do I won't merge this yet

**Comment by delthia** [comment]
Oh, well, I didn't see that issue. It makes sense, so I'll translate that in a bit and add the commit.

**Comment by delthia** [comment]
I think it should be correctly translated now

**Comment by stuarthayhurst** [comment]
Thanks. Can you take a look at the translations marked as fuzzy please? If they're all good they just need the fuzzy tag removed.

**Comment by delthia** [comment]
I've now removed the fuzzy tag from the translations I'm sure they are correct.
There are some that still have it as while I think they are "understandable", are not necessarily the best they could be.

**Comment by delthia** [comment]
I'd say that this is complete and ready for merging.

Thanks

**Pull request merged**
