### PR TITLE
Fix for RHEL9 - Gnome40

### PR DESCRIPTION
**Pull request by pakaoraki**
This will fixe #218 .
@eonpatapon @stuarthayhurst, I'm not sure about publishing a new release for Gnome 40, but this dedicated branch can be archived for people having this issue.

### CODE REVIEW

**Comment by stuarthayhurst** [comment]
Will the version to branch table in the README of the master branch need updating?

**Comment by pakaoraki** [comment]
> Will the version to branch table in the README of the master branch need updating?

We can add a note in the README if this PR is accepted.

> I'll leave release management to eon, but I personally wouldn't worry about a release for it. If anyone is still running that, they're welcome to come and manually install, but I don't think it's worth making releases for old versions.

I do agree with you, we should not maintain Caffeine for older version of gnome and we don't need to publish a new release, but I feel bad for the few users that run Caffeine in RHEL9: it can be nice to leave this dedicated branch for manual install.

**Comment by eonpatapon** [comment]
I think I can upload a new version with this, it will target gnome 40 only

**Comment by eonpatapon** [comment]
Uploaded on e.g.o

**Pull request merged**
