### PR TITLE
GNOME 3.32 - icon working

### PR DESCRIPTION
**Pull request by mirko-laruina**
This should fix the icon not showing up

### CODE REVIEW

**Comment by lfelipe1501** [comment]
thx this fix work perfectly

**Comment by jagaudin** [comment]
I was about to suggest almost the same. The only difference is that I have a method to get the icon:

    _getCustIcon: function(icon_name) {
          let gicon = Gio.icon_new_for_string( Me.dir.get_child('icons').get_path() + "/" + icon_name + ".svg" );
          return gicon;
    },

**Comment by cweagans** [comment]
@eonpatapon Any chance you could tag a release for gnome 3.32? The extension is mostly not working and I miss it very much. :)

**Comment by eonpatapon** [comment]
@cweagans you mean on ego ?

**Comment by eonpatapon** [comment]
It's now on https://extensions.gnome.org/extension/517/caffeine/

**Comment by cweagans** [comment]
yeah, thanks!!

**Pull request merged**
