### PR TITLE
Update italian translation

### LINKED ISSUE #225: Localization not working (it_IT)
Hi!

This extension doesn't load the right localization in my system (it_IT).
I found the right locale folder in the extension directory, but nothing is translated.

Cheers!

### PR DESCRIPTION
**Pull request by pakaoraki**
It will replace #221 and close #225.

This translation is updated to the recent code change and based on the previous proposal made by @albanobattistella with 3 new additions:

```
msgid " minutes"
msgstr ""
msgstr " minuti"
```

```
msgid "Durations"
msgstr ""
msgstr "Durate"
```

```
#: preferences/generalPage.js:217
msgid "Set to "
msgstr ""
msgstr "Impostato su "
```

### CODE REVIEW

**Comment by pakaoraki** [comment]
@amivaleo @albanobattistella let me know if you want to correct or change something.

**Review by stuarthayhurst — CHANGES_REQUESTED** [review]
Can the fuzzy translations be fixed? I don't know whether they're correct or not as I don't speak Italian, but ideally all translations strings marked with `#fuzzy` would be reviewed, corrected if needed, and have the `#fuzzy` tag removed.

Other than that, thanks for starting this :)

**Comment by amivaleo** [comment]
> @amivaleo @albanobattistella let me know if you want to correct or change something.

They're correct. :)

**Comment by pakaoraki** [comment]
Fuzzy tag removed ;-)

> msgid "Caffeine disabled"
> msgstr "Caffeine disabilitato"

@amivaleo I need your help for this one: is it "disabilitato" or "disabilitata" ?

**Review by stuarthayhurst — APPROVED** [review]
I can't comment on the strings themselves, but I'm happy with this :)

**Pull request merged**
