### PR TITLE
Use quick settings toggle subtitle on GNOME 44

### PR DESCRIPTION
**Pull request by DaPigGuy**
#236

### CODE REVIEW

**Comment by stuarthayhurst** [comment]
Looks good to me, works on GNOME OS Nightly.

I'll leave this for a short bit, just to make sure everyone is in agreement about the change :)

**Comment by eonpatapon** [comment]
How does that looks ?

**Comment by stuarthayhurst** [comment]
image

**Comment by pakaoraki** [comment]
I just tested it on last GnomeOS/Gnome 44 and it looks really good.

**Review by stuarthayhurst — APPROVED** [review]

**Pull request merged**
