### PR TITLE
Add support for Gnome 3.32

### PR DESCRIPTION
**Pull request by julianxhokaxhiu**
Tested, works.

### CODE REVIEW

**Comment by aifrs12** [comment]
Fixed the no icon bug?

**Comment by julianxhokaxhiu** [comment]
On my side all the icons works just fine. Although I'm using another two extensions to add support for systray icons ( appindicator and TopIcons Plus ), so it could be I'm not impacted by this.

Nevertheless everything works smooth on 3.32.

**Comment by Mr-Monkey** [comment]
This change doesn't seem to fix the missing icon for me. Anyone else?

**Comment by aifrs12** [comment]
Still not working. The Extension works great, but no icon on top bar

**Comment by julianxhokaxhiu** [comment]
Again, the icon will never appear as it requires a systray, which GNOME definitely removed some releases ago.

If you want the icon, you need other two extensions which re-create the systray support ( appindicator and/or TopIcons Plus ).

I don't see how this PR should be kept open because of an Icon support. This wasn't "officially" supported also on 3.30, yet the extension was tagged.

**Comment by NickCis** [comment]
#137 Fixes the icon

**Comment by eonpatapon** [comment]
Fixed by #137

**Pull request closed without merging**
