### PR TITLE
Update Hungarian translation

### PR DESCRIPTION
**Pull request by infeeeee**

### CODE REVIEW

**Comment by stuarthayhurst** [comment]
Sorry, I messed up and the translation files are slightly out of date
I'll push the corrected ones and this will probably need a rebase

**Comment by infeeeee** [comment]
Yeah, something was fishy for me. But I compared to other languages, and the strings were the same. Let me know when  I should check again.

**Comment by stuarthayhurst** [comment]
`master` has the correct files now, sorry about that. You should be good to check again now, there shouldn't be a huge difference between the old and new versions.

**Comment by stuarthayhurst** [comment]
`master` has changed significantly, it's now a different file you have to update, you should find it as `caffeine@patapon.info/locale/hu.po`.

**Comment by pakaoraki** [comment]
Replaced by #291

**Pull request closed without merging**
