### PR TITLE
Update JS syntax

### PR DESCRIPTION
**Pull request by NickCis**
It updates JS syntax to met [new standards](https://2017.guadec.org/wp-content/uploads/2017/06/Philip-Chimento-GUADEC-2017-Modern-Javascript-in-GNOME.pdf)

- Removes the use of `Lang.bind` (uses native `.bind`)
- Uses arrow functions instead of binding anonymous functions
- Uses classes instead of `Lang.Class`
- Uses `.includes( ... )` instead of `.indexOf( ... ) !== -1`
- Uses string templates

### CODE REVIEW

**Comment by eonpatapon** [comment]
I'm not against merging this but I need some feedback that it works properly, If someone can test this

**Comment by NickCis** [comment]
Ok!
@mirko-laruina @jagaudin @lfelipe1501 @cweagans Could you help me test it?. Thanks :)

**Comment by jagaudin** [comment]
Sure, I can test it over the weekend.

**Comment by mirko-laruina** [comment]
I've been using it since yesterday and all the features seem to be working fine, with no errors in the log.
Let's wait for other feedbacks. Anyway, you did a great job!

**Comment by cweagans** [comment]
seems good to me

**Comment by jagaudin** [comment]
I tried hard to get it to fail but to no avail. I think it's fine.

**Comment by NickCis** [comment]
Thank you! :)

**Comment by eonpatapon** [comment]
Thanks for testing, thanks @NickCis  

I'm merging it

**Comment by eonpatapon** [comment]
Are we sure it still compatible with 3.26 / 3.28 ?

**Comment by mirko-laruina** [comment]
@eonpatapon not so much, from what I've read, the ES6 classes break all previous compatibility

**Comment by NickCis** [comment]
@eonpatapon 
According to the [Guadec presentation](https://2017.guadec.org/wp-content/uploads/2017/06/Philip-Chimento-GUADEC-2017-Modern-Javascript-in-GNOME.pdf):
- Native .bind: gnome 3.8?
- Arrow Functions: gnome 3.8
- Classes: gnome 3.26
- `.includes( ... )`: Gnome 3.26
- string templates: Gnome 3.24

I really couldn't found gnome version numbers on official gnome documentation ([gjs wiki](https://gitlab.gnome.org/GNOME/gjs/wikis/home) or [devdocs](https://devdocs.baznga.org)). Nor tested on GNOME 3.26

**Comment by jagaudin** [comment]
I've tried on a CentOS 7 virtual machine running gnome 3.28 and I got an error:

    TypeError: GObject.registerClass() used with invalid base class (is PanelMenuButton)

**Comment by NickCis** [comment]
Apparently the support for `GObject.registerClass`, was introduced in [gjs 1.49.90](https://gitlab.gnome.org/GNOME/gjs/blob/master/NEWS#L904). But, I can't really find the corresponding Gnome version.

For what @jagaudin is saying, might it be 3.30?

**Comment by jagaudin** [comment]
I got the exact same error on an Ubuntu 18.10 virtual machine running gnome 3.30.
Trying googling the error just gave me a [Fedora unanswered question](https://ask.fedoraproject.org/en/question/134168/kstatusnotifieritemappindicator-extension-not-working-in-fedora-29/) that is not particularly helpful.

**Comment by mirko-laruina** [comment]
The first Gnome version requiring gjs > 1.49.90 is the 3.31.92 (https://gitlab.gnome.org/GNOME/gnome-shell/commit/6349f0feb1eb82968cfba13b94bde053efd5c979), so that should be also the first to support `GObject.registerClass`.

This is based on reading the `meson.build` from https://gitlab.gnome.org/GNOME/gnome-shell/tags

**Comment by NickCis** [comment]
Ok, I'll send the PR with the metadata corrected, thanks @jagaudin @mirko-laruina !.

Sorry for not checking that! :disappointed:

**Pull request merged**
